[package]
name = "toulousefeu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "1.0.7"
anyhow = "1.0.75"
csv = "1.3.0"