[package]
name = "toulousefeu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "1.0.5"
image = "0.24.6"
anyhow = "1.0.72"
csv = "1.2.2"
serde = "1.0.174"